name: compressed-size

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # https://github.com/marketplace/actions/checkout
      - uses: preactjs/compressed-size-action@v2 # https://github.com/marketplace/actions/compressed-size-action
