name: deploy-supabase-functions

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/**'

jobs:
  deploy-supabase-functions:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4 # https://github.com/marketplace/actions/checkout

      - uses: supabase/setup-cli@v1 # https://github.com/marketplace/actions/supabase-cli-action

      - name: create-env
        run: |
          echo "ACCESS_CONTROL_ALLOW_ORIGIN=${{ secrets.ACCESS_CONTROL_ALLOW_ORIGIN }}" >> .env

      - name: set-env
        run: |
          supabase secrets set --env-file .env --project-ref $SUPABASE_PROJECT_ID

      - name: deploy-supabase-functions
        run: |
          supabase functions deploy --project-ref $SUPABASE_PROJECT_ID
