name: pkg-size

on:
  pull_request:
    branches:
      - main

jobs:
  pkg-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # https://github.com/marketplace/actions/checkout
      - uses: actions/setup-node@v4 # https://github.com/marketplace/actions/setup-node-js-environment
        with:
          node-version: 'lts'
      - uses: pkg-size/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
