name: pkg-size

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  pkg-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # https://github.com/marketplace/actions/checkout
      - uses: actions/setup-node@v4 # https://github.com/marketplace/actions/setup-node-js-environment
      - uses: actions/setup-node@v4
      - uses: pkg-size/action@v1 # https://github.com/marketplace/actions/pkg-size-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
